apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-config
  namespace: {{ include "ecommerce-app.namespace" . }}
  labels:
{{ include "ecommerce-app.labels" . | indent 4 }}
    component: config
    app: ecommerce
    version: {{ default "v1.0.0" .Values.global.version }}
data:
  REACT_APP_ENVIRONMENT: {{ quote .Values.config.reactAppEnvironment }}
  REACT_APP_API_URL: {{ quote .Values.config.reactAppApiUrl }}
  NODE_ENV: {{ quote .Values.config.nodeEnv }}
  LOG_LEVEL: {{ quote .Values.config.logLevel }}
  REDIS_HOST: {{ quote .Values.config.redisHost }}
  REDIS_PORT: {{ quote .Values.config.redisPort }}
